### ISSUE TITLE
INFOGRAFIA-CDS-EDUARDO-TOMAS-6US

### ISSUE THREAD

**Issue by ToniDepp** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-ToniDepp#1]
[INFOGRAFÍA-6US-IS-U4.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-ToniDepp/files/15460946/INFOGRAFIA-6US-IS-U4.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 17
